### ISSUE TITLE
Huawei B310s-22

### ISSUE THREAD

**Issue by liqiz-one** [RealEnder/imeigen#1]
Hello,
could you please add this device?

![huawei](https://user-images.githubusercontent.com/53612144/179524457-96760d57-8170-4f52-96e4-b7808d9615d9.jpeg)
![huawei-b310s-22](https://user-images.githubusercontent.com/53612144/179525203-f4303228-458b-4886-bd58-c9f6d40810fa.jpg)
![huawei2](https://user-images.githubusercontent.com/53612144/179525866-7e714670-5470-4fb5-a9ae-6b745629143a.jpeg)
![huawei3](https://user-images.githubusercontent.com/53612144/179527404-e51347f8-d25c-4df1-82e1-558a33c5da83.jpeg)

Thx.

**Comment by RealEnder** [comment]
Hi,
imeigen is very simple generator for password candidates, which are part of the IMEI of the device. This is not the case for these Huawei devices. Currently the default password generation algorithm is unknown. We have a lot of these submitted to [wpa-sec](https://wpa-sec.stanev.org), so will take a closer look on the device.

**Comment by liqiz-one** [comment]
Ok, thanks for answer.
